### ISSUE TITLE
`data` must be uniquely named but has duplicate columns

### ISSUE THREAD

**Issue by zhewa** [compbiomed/singleCellTK#182]
In Data Summary & Filtering panel under Visualize tab, if I select `boxplot` in Visualization Method, `sample` as Condition, and some random gene and hit Plot, it shows a green checkmark on the right of the button "Plot" and shows this error on the right: 
```
Error: `data` must be uniquely named but has duplicate columns
```
I have checked the row names and gene names are unique for this sctk object. Let me know who I should share this data to so you can regenerate the error.
I am using `singleCellTK` version 1.2.3 downloaded from `RELEASE_3_8` branch.

**Comment by mmkhan19** [comment]
Still looking into this. The data looks similar to the ones we have used previously and is working but it fails for this particular dataset. Looks like the issue is from ggplot2 package, I did upgrade the package but no luck. Will keep you all posted. Thanks.

**Comment by joshua-d-campbell** [comment]
These tabs and functions have been refactored in version 2.0.0.
