### ISSUE TITLE
`plotLabels` does not work for plotRunPerCellQCResults

### ISSUE THREAD

**Issue by zhewa** [compbiomed/singleCellTK#402]
https://github.com/compbiomed/singleCellTK/blob/b4346f191dea4f5bece59cca3033610292c341e1/R/ggPerQCWrapper.R#L51-L74
https://github.com/compbiomed/singleCellTK/blob/b4346f191dea4f5bece59cca3033610292c341e1/R/ggPerQCWrapper.R#L96-L114
Here `plotLabels` should be `plotLabels` which passes the variable in the environment instead of hard-coded. Might need to check how other arguments in this function are passed and maybe other functions too. I'm running this function from command line.

**Comment by ykoga07** [comment]
Closed; Pull request: Devel - Modifications to plotting functions #468
