### ISSUE TITLE
replace shiny-directory-input with shinyFiles

### ISSUE THREAD

**Issue by fangpingmu** [compbiomed/singleCellTK#426]
Your application cannot be deployed as a shiny server. I debugged the problem. It seems that shiny-directory-input is the root cause. This shiny-directory-input widget only works on local shiny apps since it makes calls OS shell calls to display a directory dialog.

I believe that your app use shiny-directory-input  to display directory on the shiny server side. shinyFiles (https://github.com/thomasp85/shinyFiles ) extends the functionality of shiny by providing an API for client side access to the server file system. Can you change shiny-directory-input dependencies to shinyFiles so that this app can be deployed as a shiny server? It seems that you already used shinyFiles to parse directory input.

**Comment by joshua-d-campbell** [comment]
Hi @fangpingmu, thanks for brining this to our attention. We will try to update this in the master branch in the next month or so.

**Comment by mvfki** [comment]
Hi @fangpingmu , I have already updated that part. Would you please try to pull from our latest master branch and see if it works?

**Comment by fangpingmu** [comment]
Yes. I works. Thanks a lot. I will close this ticket.
