### ISSUE TITLE
Enchancement: sparse matrix option for importSTARsolo and similar

### ISSUE THREAD

**Issue by mbatiuk** [compbiomed/singleCellTK#433]
Hi,

I was wondering if there is a way to add sparse matrix (dgCMatrix) as an option during data import (singleCellTK::importSTARsolo and similar)

Currently class parameter specifies Matrix and matrix. Adding dgCMatrix would make sparse matrix inside sce objects this way saving a lot of storage space and RAM in large projects

Converting after import with something like assay(sce) %<>% as("dgCMatrix") works but takes a lot of time

Thanks

**Comment by joshua-d-campbell** [comment]
Hi @mbatiuk, technically setting the option to "Matrix" for the "class" parameter should make the underlying data a sparse matrix using classes from the "Matrix" package. If this does not work, let us know and I will reopen the issue.
