### ISSUE TITLE
useAssay should be raw counts in seuratFindHVG

### ISSUE THREAD

**Issue by zhewa** [compbiomed/singleCellTK#467]
Here I think the default setting `useAssay = "seuratNormData"` should be `useAssay = "counts"`. Seurat uses the raw counts to do VST.

https://github.com/compbiomed/singleCellTK/blob/c2c0f1900a58bf51ad06cc254952591ff365dfa9/R/seuratFunctions.R#L121

https://github.com/satijalab/seurat/issues/2641

**Comment by irzamsarfraz** [comment]
I have verified from the seurat github code and this appears to be true. For the "vst" method, the function uses the counts slot of the seurat object, while for other methods, it uses the data slot (which usually has the normalized data). However, in our wrapper function, even when the user specifies a normalized assay against this parameter, the .convertSCEtoSeurat() function still sets the first available assay to the counts slot by default. This therefore allows the seurat function to still use the counts assay (or the first available assay) in the input object with the "vst" method. 

Now I see that this may cause some unexpected behavior:
1. If only one assay is available in the input object, then the specified assay (being the only one) will be used by "vst" method.
2. If multiple assays are present, the user specified assay if not the first one, will not actually be used with the "vst" method and thus the parameter becomes redundant and misleading. 

I propose the following changes to avoid this behavior:
1. Set the default `useAssay` parameter to counts as suggested by @zhewa, but additionally add information about the recommended assays for all of these methods in the roxygen doc.
2. As this is a particular case, I can set the default assay position for "vst" method to counts slot and the for others to the data slot.

Let me know if I should proceed with this approach @joshua-d-campbell and thanks @zhewa for identifying this!
