### ISSUE TITLE
How to import cellranger v3 samples to shiny app

### ISSUE THREAD

**Issue by fangpingmu** [compbiomed/singleCellTK#564]
When I import cellranger v3 samples to shiny app, the row name is ENSEMBL IDs. When you run QC & Filtering, it always gives the following errors. Under collectionName - Select a Gene Set for Quality Control, I have chosen Human Mitochondrial Genes (ENSEMBL) or import gene sets (select Import mitochondrial gene set, Species: Human, ID Type: ensembl, Location: rownames, or ID Type: symbol, Location: feature_name) 

Mon Feb 21 18:49:44 2022 ... Running 'perCellQCMetrics'
Mon Feb 21 18:49:46 2022 ... Running 'scDblFinder'
Warning in scDblFinder(sce[sel_features, x], clusters = clusters, dims = dims,  :
  scDblFinder might not work well with very low numbers of cells.
Warning: Error in : BiocParallel errors
  1 remote errors, element index: 1
  11704 unevaluated and other errors
  first remote error: An error occured while processing sample 'AAACCCAAGCGCCCAT-1':
Error in dimnamesGets(x, value): invalid dimnames given for "dgCMatrix" object

  [No stack trace available]

sce <- importCellRanger(
  cellRangerDirs = "pbmc_10k",
  sampleDirs = "",
  sampleNames = "",
  dataType = "filtered")

I can change the rownames to feature_name through command line interface. 

rownames(sce) <- rowData(sce)$feature_name

When example datasets are imported, the rownames are gene symbol.

## altExpNames(0):

How can I change the rownames through shiny interface? Or how to fix the above errors at QC & Filtering step?

**Comment by rz2333** [comment]
Hi Fangping, 

Happy to help! After you imported the dataset to shiny interface, you can scroll down to the bottom of the 'Data' page and you will see the 'Set Feature for Display'. Usually, if you set it as 'feature_name' for cellranger V3 data, it should use gene_symbol as the rownames in the following analysis. 
![Screen Shot 2022-02-27 at 10 14 36 PM](https://user-images.githubusercontent.com/16445398/155918792-812b686b-9517-48ab-a14a-ce8ca45ba37f.png)

However, I noticed that the rowname might not cause the error message you saw. It is related to the 'scDblFinder' step. I guess you might select the wrong sample label on the 'QC & Filtering' page. In the 'Select variable containing sample labels' field, you need to select the value that represents the sample label of your cells (This is one of the colnames in the colData of SCE object). Please see the screenshot below. 

![Screen Shot 2022-02-27 at 10 17 21 PM](https://user-images.githubusercontent.com/16445398/155918560-85202745-be4e-4769-b32c-668b42a290fc.png)

Let me know if you still have any questions. 

Rui

**Comment by fangpingmu** [comment]
Thank you. "Select variable containing sample labels" is the problem. 

It seems that "Set Feature to Display" only change the display features. The rownames does not change. Under collectionName, I still need to choose "Human Mitochondrial Genes (Ensembl)". However, this does not matter. 
 
<img width="368" alt="Screen Shot 2022-02-28 at 9 23 15 AM" src="https://user-images.githubusercontent.com/17434395/155999311-088a86f1-09de-4919-a197-0fcd5786e244.png">
