### ISSUE TITLE
Error at Dimension Reduction under Feature Selection & Dimensionality Reduction

### ISSUE THREAD

**Issue by fangpingmu** [compbiomed/singleCellTK#570]
I am using shiny app version 2.4.1. I have uploaded example dataset PBMC 3K.

Thu Mar  3 11:16:28 2022 ... Starting Dimensionality Reduction: 'scaterPCA'.
Thu Mar  3 11:16:28 2022 ... Computing Scater PCA.
Thu Mar  3 11:16:41 2022 ... Ending Dimensionality Reduction.
Thu Mar  3 11:16:41 2022 ... Generating Elbow Plot.
Thu Mar  3 11:16:41 2022 ... Generating Heatmaps.
Warning: Error in <Anonymous>: cannot open file 'Rplots.pdf'
  [No stack trace available

<img width="400" alt="Screen Shot 2022-03-03 at 11 18 41 AM" src="https://user-images.githubusercontent.com/17434395/156607681-a72afafa-ba12-44ec-8d1a-0b4615569def.png">
]

**Comment by fangpingmu** [comment]
I debugged this problem. This looks like a plotly problem discussed in this issue https://github.com/plotly/plotly.R/issues/494

The consensus is to add pdf(NULL) to server.R function where the plot is generated. I can confirm that this problem appears when "Compute HeatmapPlot?" is selected. 

https://github.com/compbiomed/singleCellTK/blob/master/inst/shiny/server.R

Where can I try to add pdf(NULL)?

**Comment by joshua-d-campbell** [comment]
This has been fixed in version [v2.5.1](https://github.com/compbiomed/singleCellTK/releases/tag/v2.5.1).
