### ISSUE TITLE
'mitoGeneLocation' not specified

### ISSUE THREAD

**Issue by fangpingmu** [compbiomed/singleCellTK#583]
I am using docker container campbio/sctk_shiny:v2.5.1. I have uploaded PBMC 3K (10X) Example Dataset.

Mon Apr 18 15:59:28 2022 ... Running 'perCellQCMetrics'
'mitoGeneLocation' not specified or specified as NULL. Skip quantifying mitochondrial genes

<img width="351" alt="Screen Shot 2022-04-18 at 4 00 44 PM" src="https://user-images.githubusercontent.com/17434395/163869621-2a8d52eb-eadd-4c48-94cd-b27bae2c520e.png">
.

**Comment by rz2333** [comment]
Hi, 

Thanks for reporting. This issue might be a bug in the warning message. We will fix that as soon as possible. 

Rui

**Comment by mvfki** [comment]
I've already fixed this at some point recently. A new release will be soon.

**Comment by mvfki** [comment]
99e76b9c3899ca13df27dea871b9e1b183bb1636

**Comment by mvfki** [comment]
@fangpingmu The new version of SCTK Shiny APP is available on Docker Hub (version 2.7.1 https://hub.docker.com/r/campbio/sctk_shiny). The issue you previously mentioned should have already been resolved. We would appreciate it if you can have a chance to try it out and please feel free to report any further issue. 

Best,
Yichen
