### ISSUE TITLE
I can not select proper directories to upload data in shiny app

### ISSUE THREAD

**Issue by shoma-tsubota** [compbiomed/singleCellTK#601]
When I try to upload files, I can not select directories in my PC as shown in attached screenshot.
My files are stored in D drive, but can not choose it. I am not sure if it problems in my PC. 
![image](https://user-images.githubusercontent.com/85160893/175761153-9824f7ba-1847-4c19-a8ed-e1a0f6e07fe5.png)

**Comment by mvfki** [comment]
Hi @shoma-tsubota , 

Thank you a lot for the feedback. To debug this, we will need to know some more information. Would do mind sharing your answers for:
- Are you running this SCTK instance from your local PC (after installing the package), or are you connecting to the online server?
- Could you please share the session info if you are starting this APP from your local PC? (with R command `sessionInfo()`)

Honestly, we are already aware of an issue related to data uploading. The implementation currently only reads files in the same system as the APP, which means we cannot upload our files from a PC to an SCTK APP running on a remote server. We are already working on fixing this issue. However, this only happens to the upload for data generated by preprocessing tools (e.g. cellranger, starSolo, etc. ). Users can still correctly upload an RDS file of either a `SingleCellExperiment` object or a `Seurat` object. If you could identify that the issue you are faced with is the same as this one, then a workaround would be using RDS file to upload.

**Comment by shoma-tsubota** [comment]
Hi @mvfki , 

Thank you for your quick reply. I simply accessed to the online server (https://sctk.bu.edu/) and faced the trouble.
You mean you can not load and upload files stored in local device?

**Comment by mvfki** [comment]
Unfortunately, for the online server, we cannot upload file from local device for now. However, you can download and [install](https://camplab.net/sctk/v2.6.0/articles/installation.html) the package to your PC and work from there. 

We are already working on the upload issue and hope we can get this out soon.

**Comment by shoma-tsubota** [comment]
I understand and appreciate that you are working on this issue. Then, I will try the package using R. Thanks a lot!
