### ISSUE TITLE
reportCellQC error

### ISSUE THREAD

**Issue by jopeptid** [compbiomed/singleCellTK#603]
Thank you for developing this great tool. It helps a lot with quality control of my scRNA-seq data. I have been running into a problem when running "reportCellQC". I tested it in singleCellTK 2.6.0 and 2.7.1 and it gives exactly the same error.
Thank you for looking into this.

I run the QC (which runs fine as far I can tell; it generates all requested output columns)

  > scef <- runCellQC(scef, 
                    algorithms = c("QCMetrics","doubletFinder","decontX_bg","scrublet"),
                    background = sce.bkg,
                    paramsList = list(doubletFinder=list(formationRate=0.07)),
                    # bgAssayName = "counts",
                    mitoGeneLocation = "rownames",
                    mitoPrefix = "^mt-"
  )

When I run 

> reportCellQC(scef, output_file = paste0(fname,"_test.html"), output_dir = QC.dir)

I get following output:

processing file: CellQC.Rmd
  |..                                                                                                                     |   1%
   inline R code fragments

  |...                                                                                                                    |   3%
label: CellQC-lib (with options) 
List of 2
 $ warning: logi FALSE
 $ include: logi FALSE

  |.....                                                                                                                  |   4%
  ordinary text without R code

  |......                                                                                                                 |   5%
label: CellQC-import (with options) 
List of 2
 $ eval   : logi TRUE
 $ include: logi FALSE

  |........                                                                                                               |   6%
   inline R code fragments

  |.........                                                                                                              |   8%
label: Introduction (with options) 
List of 5
 $ echo     : logi FALSE
 $ results  : chr "asis"
 $ fig.align: chr "center"
 $ warning  : logi FALSE
 $ message  : logi FALSE

  |...........                                                                                                            |   9%
  ordinary text without R code

  |............                                                                                                           |  10%
label: runPerCellQC-description (with options) 
List of 3
 $ include: logi FALSE
 $ warning: logi FALSE
 $ message: logi FALSE

  |..............                                                                                                         |  12%
  ordinary text without R code

  |...............                                                                                                        |  13%
label: SummaryStats (with options) 
List of 5
 $ echo     : logi FALSE
 $ results  : chr "asis"
 $ fig.align: chr "center"
 $ warning  : logi FALSE
 $ message  : logi FALSE

  |.................                                                                                                      |  14%
  ordinary text without R code

  |...................                                                                                                    |  16%
label: General quality control metrics (with options) 
List of 5
 $ results  : chr "asis"
 $ fig.align: chr "center"
 $ warning  : logi FALSE
 $ message  : logi FALSE
 $ echo     : logi FALSE

  |....................                                                                                                   |  17%
  ordinary text without R code

  |......................                                                                                                 |  18%
label: plotsQCMetrics-plot (with options) 
List of 6
 $ results  : chr "asis"
 $ eval     : logi TRUE
 $ fig.align: chr "center"
 $ warning  : logi FALSE
 $ message  : logi FALSE
 $ echo     : logi FALSE

  |.......................                                                                                                |  19%
   inline R code fragments

  |.........................                                                                                              |  21%
label: Doublet Summary (with options) 
List of 7
 $ fig.width : num 15
 $ fig.height: num 5
 $ results   : chr "asis"
 $ fig.align : chr "center"
 $ warning   : logi FALSE
 $ message   : logi FALSE
 $ echo      : logi FALSE

Quitting from lines 320-391 (CellQC.Rmd) 
Error: subscript contains invalid names

> sessionInfo() R version 4.2.1 (2022-06-23) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 20.04.4 LTS  Matrix products: default BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats4    stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] diem_2.4.0                  cowplot_1.1.1               forcats_0.5.1               stringr_1.4.0                [5] dplyr_1.0.9                 purrr_0.3.4                 readr_2.1.2                 tidyr_1.2.0                  [9] tibble_3.1.7                ggplot2_3.3.6               tidyverse_1.3.1             RColorBrewer_1.1-3          [13] patchwork_1.1.1             data.table_1.14.2           scuttle_1.6.2               singleCellTK_2.7.1          [17] DelayedArray_0.22.0         Matrix_1.4-1                SingleCellExperiment_1.18.0 SummarizedExperiment_1.26.1 [21] Biobase_2.56.0              GenomicRanges_1.48.0        GenomeInfoDb_1.32.2         IRanges_2.30.0              [25] S4Vectors_0.34.0            BiocGenerics_0.42.0         MatrixGenerics_1.8.1        matrixStats_0.62.0          [29] harmony_0.1.0               Rcpp_1.0.8.3                sp_1.5-0                    SeuratObject_4.1.0          [33] Seurat_4.1.1                future_1.26.1               reticulate_1.25             pacman_0.5.1                 loaded via a namespace (and not attached):   [1] TMB_1.9.0                     graphlayouts_0.8.0            pbapply_1.5-0                 haven_2.5.0                     [5] lattice_0.20-45               dyndimred_1.0.4               vctrs_0.4.1                   V8_4.2.0                        [9] dynwrap_1.2.2                 GSVAdata_1.32.0               mgcv_1.8-40                   blob_1.2.3                     [13] survival_3.3-1                dynutils_1.0.9                spatstat.data_2.2-0           later_1.3.0                    [17] nloptr_2.0.3                  R.utils_2.12.0                DBI_1.1.3                     rappdirs_0.3.3                 [21] uwot_0.1.11.9000              dqrng_0.3.0                   enrichR_3.0                   zlibbioc_1.42.0                [25] rgeos_0.5-9                   htmlwidgets_1.5.4             GlobalOptions_0.1.2           hdf5r_1.3.5                    [29] leiden_0.4.2                  multipanelfigure_2.1.2        Libra_1.0.0                   scater_1.24.0                  [33] lmds_0.1.0                    parallel_4.2.1                irlba_2.3.5                   tidygraph_1.2.1                [37] KernSmooth_2.23-20            carrier_0.1.0                 promises_1.2.0.1              limma_3.52.2                   [41] dbscan_1.1-10                 graph_1.74.0                  magick_2.7.3                  RcppParallel_5.1.5             [45] apcluster_1.4.10              fs_1.5.2                      assertive.types_0.0-3         textshaping_0.3.6              [49] fastmatch_1.1-3               digest_0.6.29                 png_0.1-7                     sctransform_0.3.3              [53] scatterpie_0.1.7              DOSE_3.22.0                   ggraph_2.0.5                  pkgconfig_2.0.3                [57] GO.db_3.15.0                  spatstat.random_2.2-0         DelayedMatrixStats_1.18.0     ggbeeswarm_0.6.0               [61] iterators_1.0.14              minqa_1.2.4                   DropletUtils_1.16.0           clusterProfiler_4.4.4          [65] spam_2.8-0                    beeswarm_0.4.0                circlize_0.4.16               bslib_0.3.1                    [69] xfun_0.31                     GetoptLong_1.0.5              zoo_1.8-10                    tidyselect_1.1.2               [73] reshape2_1.4.4                ica_1.0-2                     viridisLite_0.4.0             rtracklayer_1.56.1             [77] rlang_1.0.3                   jquerylib_0.1.4               glue_1.6.2                    ensembldb_2.20.2               [81] modelr_0.1.8                  fields_13.3                   ggsignif_0.6.3                DESeq2_1.36.0                  [85] kableExtra_1.3.4              labeling_0.4.2                httpuv_1.6.5                  pbmcapply_1.5.1                [89] assertive.base_0.0-9          BiocNeighbors_1.14.0          DO.db_2.9                     webshot_0.5.3                  [93] annotate_1.74.0               MCMCprecision_0.4.0           jsonlite_1.8.0                XVector_0.36.0                 [97] bit_4.0.4                     mime_0.12                     systemfonts_1.0.4             Rsamtools_2.12.0              [101] gridExtra_2.3                 assertive.properties_0.0-5    stringi_1.7.6                 processx_3.6.1                [105] spatstat.sparse_2.1-1         scattermore_0.8               rhdf5filters_1.8.0            yulab.utils_0.0.5             [109] rgdal_1.5-32                  bitops_1.0-7                  cli_3.3.0                     maps_3.4.0                    [113] RSQLite_2.2.14                rstudioapi_0.13               GenomicAlignments_1.32.0      nlme_3.1-158                  [117] qvalue_2.28.0                 locfit_1.5-9.5                listenv_0.8.0                 miniUI_0.1.1.1                [121] gridGraphics_0.5-1            R.oo_1.25.0                   dbplyr_2.2.1                  readxl_1.4.0                  [125] lifecycle_1.0.1               ExperimentHub_2.4.0           munsell_0.5.0                 cellranger_1.1.0              [129] R.methodsS3_1.8.2             proxyC_0.2.4                  codetools_0.2-18              vipor_0.4.5                   [133] lmtest_0.9-40                 assertive.files_0.0-2         xtable_1.8-4                  ROCR_1.0-11                   [137] BiocManager_1.30.18           WebGestaltR_0.4.4             abind_1.4-5                   farver_2.1.0                  [141] parallelly_1.32.0             AnnotationHub_3.4.0           RANN_2.6.1                    aplot_0.1.6                   [145] BiocIO_1.6.0                  ggtree_3.4.0                  scWGCNA_0.0.0.9000            celldex_1.6.0                 [149] RcppAnnoy_0.0.19              ggeasy_0.1.3                  goftest_1.2-3                 cluster_2.1.3                 [153] future.apply_1.9.0            svMisc_1.2.3                  tidytree_0.3.9                ellipsis_0.3.2                [157] prettyunits_1.1.1             reprex_2.0.1                  lubridate_1.8.0               ggridges_0.5.3                [161] colorRamps_2.3.1              igraph_1.3.2                  RcppEigen_0.3.3.9.2           fgsea_1.22.0                  [165] remotes_2.4.2                 lmerTest_3.1-3                glmmTMB_1.1.3                 spatstat.utils_2.3-1          [169] htmltools_0.5.2               BiocFileCache_2.4.0           GenomicFeatures_1.48.3        scRNAseq_2.10.0               [173] yaml_2.3.5                    utf8_1.2.2                    plotly_4.10.0                 interactiveDisplayBase_1.34.0 [177] XML_4.0-0                     ggpubr_0.4.0.999              withr_2.5.0                   fitdistrplus_1.1-8            [181] BiocParallel_1.30.3           randomcoloR_1.1.0.1           bit64_4.0.5                   rngtools_1.5.2                [185] doRNG_1.8.2                   foreach_1.5.2                 ProtGenerics_1.28.0           Biostrings_2.64.0             [189] celda_1.12.0                  spatstat.core_2.4-4           combinat_0.0-8                progressr_0.10.1              [193] GOSemSim_2.22.0               ragg_1.2.2                    rsvd_1.0.5                    ScaledMatrix_1.4.0            [197] evaluate_0.15                 memoise_2.0.1                 geneplotter_1.74.0            tzdb_0.3.0                    [201] ps_1.7.1                      curl_4.3.2                    fansi_1.0.3                   highr_0.9                     [205] GSEABase_1.58.0               tensor_1.5                    edgeR_3.38.1                  cachem_1.0.6                  [209] desc_1.4.1                    deldir_1.0-6                  rjson_0.2.21                  rstatix_0.7.0                 [213] ggrepel_0.9.1                 clue_0.3-61                   rprojroot_2.0.3               tools_4.2.1                   [217] sass_0.4.1                    magrittr_2.0.3                RCurl_1.98-1.7                car_3.1-0                     [221] ape_5.6-2                     xml2_1.3.3                    ggplotify_0.1.0               rmarkdown_2.14                [225] httr_1.4.3                    assertthat_0.2.1              Rhdf5lib_1.18.2               AnnotationFilter_1.20.0       [229] boot_1.3-28                   globals_0.15.1                R6_2.5.1                      progress_1.2.2                [233] genefilter_1.78.0             KEGGREST_1.36.2               treeio_1.20.0                 gtools_3.9.2.2                [237] shape_1.4.6                   beachmat_2.12.0               HDF5Array_1.24.1              BiocVersion_3.15.2            [241] BiocSingular_1.12.0           rhdf5_2.40.0                  splines_4.2.1                 carData_3.0-5                 [245] ggfun_0.0.6                   colorspace_2.0-3              generics_0.1.2                pillar_1.7.0                  [249] tweenr_1.0.2                  GenomeInfoDbData_1.2.8        plyr_1.8.7                    dotCall64_1.0-1               [253] gtable_0.3.0                  rvest_1.0.2                   restfulr_0.0.15               knitr_1.39                    [257] ComplexHeatmap_2.12.0         biomaRt_2.52.0                shadowtext_0.1.2              fastmap_1.1.0                 [261] doParallel_1.0.17             AnnotationDbi_1.58.0          SingleR_1.10.0                fishpond_2.2.0                [265] broom_1.0.0                   babelwhale_1.0.3              tester_0.1.7                  UCell_2.0.1                   [269] scales_1.2.0                  filelock_1.0.2                backports_1.4.1               lme4_1.1-29                   [273] enrichplot_1.16.1             blme_1.0-5                    hms_1.1.1                     ggforce_0.3.3                 [277] Rtsne_0.16                    shiny_1.7.1                   polyclip_1.10-0               grid_4.2.1                    [281] numDeriv_2016.8-1.1           assertive.numbers_0.0-2       lazyeval_0.2.2                whisker_0.4                   [285] crayon_1.5.1                  MASS_7.3-57                   downloader_0.4                sparseMatrixStats_1.8.0       [289] viridis_0.6.2                 dynparam_1.0.2                svglite_2.1.0                 rpart_4.1.16                  [293] compiler_4.2.1                spatstat.geom_2.4-0
--

**Comment by mvfki** [comment]
Hi @jopeptid , 

Thank you so much for your feedback. 

First of all, the error message `subscript contains invalid names` is quite general, though a common scenario is when you want to extract columns from a data frame but is requesting nonexisting variables. So it would be nice if you can share what you have with the command `names(colData(scef))`. 

Meanwhile, I just tested the reporting functionality with the following code but could not get that error. From the message you showed, I thought it must be something with the doublet detection section, so I only tested the algorithms you used for doublet detection. But, if you can still see the error with the following code, then we will need to consider about it in a different way. 

```r
library(singleCellTK)
sce <- importExampleData("pbmc3k")
sce <- runCellQC(sce,
                 algorithms = c("doubletFinder","scrublet"),
                 paramsList = list(doubletFinder=list(formationRate=0.07))
)
reportCellQC(sce, output_file = "DoubletQC.html", output_dir = '.')
```

Obviously, the optimistic way to debug would be that we can find where the error happened in the RMarkdown (at `inst/rmarkdown/qc/CellQC.Rmd`) with your specific dataset. I do have something in mind for how to do this. But this will depend on if you are willing to help with it. 

Best,
Yichen

**Comment by jopeptid** [comment]
Hi Yichen,

Thanks for the speedy reply.

I think I figured it out. Something in the file structure might have changed in later releases of the SingleCellExperiment R package.
The error is not related to the algorithm. It also occurs when I run only "QCMetrics". Your code runs just fine. But if I run the following code it throws the exact same error:

> library(singleCellTK)
sce <- importExampleData("pbmc3k")
mtx = assay(sce, "counts")
sce <- SingleCellExperiment::SingleCellExperiment(list(counts=mtx)) # this is how I construct my sce
sce <- runCellQC(sce,
                 algorithms = c("QCMetrics")
)
reportCellQC(sce, output_file = "DoubletQC.html", output_dir = '.')

> package.version("SingleCellExperiment")
[1] "1.18.0"

**Comment by mvfki** [comment]
That's a great catch. I can also see the error now. We will try to fix this in the next few days. Thank you so much!

**Comment by mvfki** [comment]
I think basically it's because we assume users have a `colData` variable called `"sample"`, to specify the sample/batch belonging of each cell. But I agree it should not be taken as granted that users will always have this. A work around for you now is followed. But we will definitely have a better handling of such cases.
```r
scec$sample <- "pbmc3k" # or any string that makes sense to you
```

**Comment by jopeptid** [comment]
Hi Yichen,

Just tested it out. Runs flawlessly. Thank you so much for the fast fix. Much appreciated.

Best, Josef
