### ISSUE TITLE
error in runDropletQC

### ISSUE THREAD

**Issue by Dragonlongzhilin** [compbiomed/singleCellTK#607]
I want to remove the empty drop using runDropletQC function and encountered a problem:

Mon Aug  1 15:04:41 2022 ... Running 'perCellQCMetrics'
Mon Aug  1 15:04:45 2022 ... Running 'emptyDrops'
Error in .compute_ambient_stats(m, totals, lower = lower) :
  no counts available to estimate the ambient profile

This is my single cell data:
![image](https://user-images.githubusercontent.com/33304280/182092114-feb8d769-f8a3-46ea-b2d5-ec1f7f7226fb.png)

how to deal with this problem?

**Comment by rz2333** [comment]
Hi,

Thanks for using the sctk. Based on the number of cells in your SCE object, it seems like it has already removed the empty droplets. Before we dive into the error, some information will be helpful for us to debug:

Is the dataset generated by 10x? Could we know how did you load this dataset? Did you load the raw matrix (including empty droplet) or just the cell matrix (empty droplet removed)? 

Thanks,
Rui

**Comment by joshua-d-campbell** [comment]
Hi @Dragonlongzhilin, just to add to what Rui said, given that you have a matrix with 16,280 cells, it looks like you are already using the filtered matrix without empty drops. The raw matrix with empty drops usually has several hundred thousand columns. Therefore, you do not need to run the `runDropletQC` function but can move directly to running `runCellQC` which will calculate QC metrics for your true cells.

**Comment by joshua-d-campbell** [comment]
Hi @Dragonlongzhilin, were we able to fix your problem? If so, I will close this issue.
