### ISSUE TITLE
SCTK_runQC.R script produces error

### ISSUE THREAD

**Issue by ponomarevsy** [compbiomed/singleCellTK#641]
Dear singleCellTK developers,

I am hitting this error in both singleCellTK-2.7.1 and singleCellTK-2.7.3 conda environments when running SCTK_runQC.R example script (under RHEL 7.9):
```
Rscript /path/Anaconda3/2022.05/envs/singleCellTK-2.7.1/lib/R/library/singleCellTK/exec/SCTK_runQC.R
...
Loading required package: BiocParallel
Error in strsplit(opt[["preproc"]], ",") : non-character argument
Calls: unlist -> strsplit
Execution halted
```
The version of R is:
```
» R --version                                                                        
R version 4.1.3 (2022-03-10) -- "One Push-Up"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)
...
```
Please let me know what that means (most likely, incompatible components?). Thank you!

**Comment by joshua-d-campbell** [comment]
Hi @ponomarevsy, you need to supply the required parameters including "preproc". See this [link](https://camplab.net/sctk/current/articles/cmd_qc.html) for a description of the required parameters.

**Comment by ponomarevsy** [comment]
Yes, that makes sense, @joshua-d-campbell, and thank you. My apologies! A user told me that it works fine with the required parameters. Let's close this ticket...

**Comment by joshua-d-campbell** [comment]
Thanks so much! We will try to make this error message better in the next version. Please let us know if you have other suggestions or problems.
