### ISSUE TITLE
unable to select directory when exporting data

### ISSUE THREAD

**Issue by pcbunda** [compbiomed/singleCellTK#675]
Good day! I am trying to analyze data via the SCTK Shiny app. However, when I try to export my data using the instructions on the documentation, I am unable to select a directory to download my files. Do you happen to know a solution to this problem? Thanks in advance

**Comment by joshua-d-campbell** [comment]
Hi @pcbunda, thanks for bringing this to our attention. Just to confirm, were you using the app from our online server at sctk.bu.edu or running it locally on your own system?

**Comment by pcbunda** [comment]
Thanks for the quick response @joshua-d-campbell! I was using the app from your online server at sctk.bu.edu. This is what the export window looks like for me. I am unable to select other directories and it is always set to 'home' by default.
<img width="1434" alt="Screenshot 2023-01-07 at 10 18 53 AM" src="https://user-images.githubusercontent.com/120497209/211157908-0990bf3b-f1aa-4264-9239-4507384905db.png">

**Comment by joshua-d-campbell** [comment]
This has been fixed in v2.8.1. The new app should be online shortly at sctk.bu.edu.
