### ISSUE TITLE
In SCTK Shiny app, inability to import STARsolo outputs from GeneFull folder

### ISSUE THREAD

**Issue by apeleraux** [compbiomed/singleCellTK#678]
When importing a STARsolo sample into the SCTK shiny app, the matrix files are automatically selected from the Solo.out/Gene/filtered subfolder. However, when alignment with STARsolo is performed to include introns, matrix files are stored in the Solo.out/GeneFull/filtered subfolder. It is necessary to add the choice of which folder to use for data import in the app, Gene or GeneFull.

**Comment by joshua-d-campbell** [comment]
This has been fixed in the latest release v2.8.1.
