### ISSUE TITLE
Issue in loading cellranger files in shiny docker app 

### ISSUE THREAD

**Issue by athulmenon** [compbiomed/singleCellTK#688]
Hi Team,

Thanks for this great tool!

I am running Docker GUI version of SCTK.

` docker run -d -p 3840:3838 -v /home/athul:/data campbio/sctk_shiny:v2.7.1a`

The sctk app loads succesfully. Eventhough my cellranger outputs are kept in the mount location, when try to load it through GUI, I am not able to locate the cellranger folders (Attaching the screenshot).

![Screenshot 2023-03-03 105759](https://user-images.githubusercontent.com/17609182/222709530-008c4dc3-2a31-46a4-b7c7-42b615d4e412.png)

I am able to load flatfiles and SEURAT object, as I can browse my folders and select those files but not with the other inputs. 

I can list all the files in /home/athul when tried with this command.
` docker run -d -p 3840:3838 -v /home/athul:/data campbio/sctk_shiny:v2.7.1a ls /data`

Any help is appreciated.

Regards,
Athul

**Comment by joshua-d-campbell** [comment]
The importing tab has been updated in version 2.10.1 so it should now allow you to directly find and add the files. Note that we had to refactor the import page a bit so the format is slightly different.
