### ISSUE TITLE
Size limit for import into Shiny app

### ISSUE THREAD

**Issue by apeleraux** [compbiomed/singleCellTK#691]
I tried to upload an RDS file of about 1 GB containing a SingleCellExperiment object and got the message "Maximum upload size exceeded".  What is the limit in size for data import into the SCTK shiny app, and can it be increased?

**Comment by apeleraux** [comment]
I found the answer. The limit is defined by the shiny.maxRequestSize option at the top of the server.R file.

**Comment by joshua-d-campbell** [comment]
Just FYI, we have increased the default max file upload size to 10GB in version 2.8.1.
