### ISSUE TITLE
singularity container missing package optparse

### ISSUE THREAD

**Issue by JHYSiu** [compbiomed/singleCellTK#731]
Hi

This may be incompetency on my part, but optparse package seems to be missing from the singularity container? 

I pulled it from `singularity pull docker://campbio/sctk_qc:2.10.1` today 

I was testing if I could mount it with the following: `singularity run -B /user/project_name/:/user/project_name/ /user/project_name/packages/singleCellTK/sctk_qc_2.10.1.sif` (I tried with another container and that mounted fine)

I'm unable to run it due to the missing optparse package. (other packages such as singleCellTK load fine)

**Comment by mingl1997** [comment]
Hello,

We are in the process of releasing a new version and docker that will fix this issue.
